version: '3.3'
services:
  jspm-node:
    build: ./docker/node
    volumes:
     - ./:/src:cached
     - ./tmp/node_modules/:/src/node_modules:cached
     - ./tmp/jspm_packages/:/src/public/jspm_packages:cached
     - ./tmp/npm_cache/:/root/.npm/:cached
     - ./tmp/tmp/:/tmp/:cached
    ports:
     - "9080:9080"
    expose:
     - "9080"
    environment:
      docker: 'docker'
    command: sh -c 'echo "Waiting for npm install" && wait-on http://jspm-npm:8093 && yarn start'
    depends_on:
     - jspm-npm
  jspm-npm:
    build: ./docker/node
    command: sh -c 'npm config set loglevel info && yarn install && yarn jspm install && echo "npm install completed..." && http-server -p 8093'
    volumes:
     - yarn_cache:/root/.cache
     - ./:/src
     - ./tmp/node_modules/:/src/node_modules
     - ./tmp/jspm_packages/:/src/public/jspm_packages
     - ./tmp/npm_cache/:/root/.npm/
     - ./tmp/tmp/:/tmp/
    expose:
     - "8093"
volumes:
  yarn_cache:
